spring:
  datasource:
      password: developer
      username: postgres
      url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true